/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as StudyRouteImport } from './routes/study'
import { Route as SubjectsRouteImport } from './routes/subjects'
import { Route as StudyIndexRouteImport } from './routes/study.index'
import { Route as StudyModuleIdRouteImport } from './routes/study.$moduleId'
import { Route as SubjectsIndexRouteImport } from './routes/subjects.index'
import { Route as SubjectsSubjectIdRouteImport } from './routes/subjects.$subjectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyRoute = StudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsRoute = SubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyIndexRoute = StudyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudyRoute,
} as any)
const StudyModuleIdRoute = StudyModuleIdRouteImport.update({
  id: '/$moduleId',
  path: '/$moduleId',
  getParentRoute: () => StudyRoute,
} as any)
const SubjectsIndexRoute = SubjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SubjectsRoute,
} as any)
const SubjectsSubjectIdRoute = SubjectsSubjectIdRouteImport.update({
  id: '/$subjectId',
  path: '/$subjectId',
  getParentRoute: () => SubjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/quiz': typeof QuizRoute
  '/study': typeof StudyRouteWithChildren
  '/subjects': typeof SubjectsRouteWithChildren
  '/study/$moduleId': typeof StudyModuleIdRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdRoute
  '/study/': typeof StudyIndexRoute
  '/subjects/': typeof SubjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/quiz': typeof QuizRoute
  '/study/$moduleId': typeof StudyModuleIdRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdRoute
  '/study': typeof StudyIndexRoute
  '/subjects': typeof SubjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/quiz': typeof QuizRoute
  '/study': typeof StudyRouteWithChildren
  '/subjects': typeof SubjectsRouteWithChildren
  '/study/$moduleId': typeof StudyModuleIdRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdRoute
  '/study/': typeof StudyIndexRoute
  '/subjects/': typeof SubjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/quiz'
    | '/study'
    | '/subjects'
    | '/study/$moduleId'
    | '/subjects/$subjectId'
    | '/study/'
    | '/subjects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/quiz'
    | '/study/$moduleId'
    | '/subjects/$subjectId'
    | '/study'
    | '/subjects'
  id:
    | '__root__'
    | '/'
    | '/quiz'
    | '/study'
    | '/subjects'
    | '/study/$moduleId'
    | '/subjects/$subjectId'
    | '/study/'
    | '/subjects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QuizRoute: typeof QuizRoute
  StudyRoute: typeof StudyRouteWithChildren
  SubjectsRoute: typeof SubjectsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study': {
      id: '/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof StudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects': {
      id: '/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof SubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/': {
      id: '/study/'
      path: '/'
      fullPath: '/study/'
      preLoaderRoute: typeof StudyIndexRouteImport
      parentRoute: typeof StudyRoute
    }
    '/study/$moduleId': {
      id: '/study/$moduleId'
      path: '/$moduleId'
      fullPath: '/study/$moduleId'
      preLoaderRoute: typeof StudyModuleIdRouteImport
      parentRoute: typeof StudyRoute
    }
    '/subjects/': {
      id: '/subjects/'
      path: '/'
      fullPath: '/subjects/'
      preLoaderRoute: typeof SubjectsIndexRouteImport
      parentRoute: typeof SubjectsRoute
    }
    '/subjects/$subjectId': {
      id: '/subjects/$subjectId'
      path: '/$subjectId'
      fullPath: '/subjects/$subjectId'
      preLoaderRoute: typeof SubjectsSubjectIdRouteImport
      parentRoute: typeof SubjectsRoute
    }
  }
}

interface StudyRouteChildren {
  StudyModuleIdRoute: typeof StudyModuleIdRoute
  StudyIndexRoute: typeof StudyIndexRoute
}

const StudyRouteChildren: StudyRouteChildren = {
  StudyModuleIdRoute: StudyModuleIdRoute,
  StudyIndexRoute: StudyIndexRoute,
}

const StudyRouteWithChildren = StudyRoute._addFileChildren(StudyRouteChildren)

interface SubjectsRouteChildren {
  SubjectsSubjectIdRoute: typeof SubjectsSubjectIdRoute
  SubjectsIndexRoute: typeof SubjectsIndexRoute
}

const SubjectsRouteChildren: SubjectsRouteChildren = {
  SubjectsSubjectIdRoute: SubjectsSubjectIdRoute,
  SubjectsIndexRoute: SubjectsIndexRoute,
}

const SubjectsRouteWithChildren = SubjectsRoute._addFileChildren(
  SubjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QuizRoute: QuizRoute,
  StudyRoute: StudyRouteWithChildren,
  SubjectsRoute: SubjectsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
